### ISSUE TITLE
Bandcamp match script task list

### ISSUE THREAD

**Issue by RichRbrtsn** [rk-bibby/Music_match#1]
- [ ] Need to strip final punctuation from MARC fields 245 a
- [ ] Assign csv rows withitn Bandcamp title file to appropriate variables
- [ ] Add check for record levels to help determine if we have archived and catalogued matches.
